# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - master
      - tdd-pp-lab
      - tdd-pp-lab-complete
  schedule:
    - cron:  '0 0 * * *'

jobs:
  start-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        branch: [master]
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: pip install pipenv
    - run: pipenv install --dev
    - shell: bash
      run: |
        if pipenv run python -m pytest &> out ; then
          cat out
          exit 1
        fi
    - shell: bash
      run: |
        if ! grep -F "assert type(doorbell.ring(1)) is str" out ; then
          cat out
          exit 1
        fi

  completed-versions:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        branch: [tdd-pp-lab, tdd-pp-lab-complete]
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: pip install pipenv
    - run: pipenv install --dev
    - run: pipenv run python -m pytest
